### ISSUE TITLE
Visual bugs (pong and chat)

### ISSUE THREAD

**Issue by BeBel42** [maxdesalle/ft_transcendence#14]
Don't pay attention to the console here.
Visual bug for pong:
- play a pong against anyone
- scroll down
- you'll see a white bar thingy that does not look right.

<img width="1243" alt="visual bug pong" src="https://user-images.githubusercontent.com/64377698/185796551-ab85c55f-3051-4086-a1d7-ec39f2ddaf9b.png">
.
Visual bug for chat:
- be in a chat room
- make the window small in height
- the "enter message" field cannot be seen anymore..

<img width="1269" alt="Enter message bug" src="https://user-images.githubusercontent.com/64377698/185796550-dddfb7ce-580a-4377-bafe-4667bb746964.png">

**Comment by dbanziziki** [comment]
it's fixed on the users_status branch I will merge soon

**Comment by dbanziziki** [comment]
> it's fixed on the users_status branch I will merge soon

the branch was merged it's on main now
