### ISSUE TITLE
Firefox warning cookie

### ISSUE THREAD

**Issue by BeBel42** [maxdesalle/ft_transcendence#15]
- login with 42 on firefox
- the console will display the warning: 'Cookie “jwt_token” with the “SameSite” attribute value “Lax” or “Strict” was omitted because of a cross-site redirect. [127.0.0.1:3000](http://127.0.0.1:3000/)'

**Comment by cammarosano** [comment]
This problem does not happen when the frontend is served as static files (as CORS is no longer needed).
You can try it on the main branch: `docker-compose up`

I think we can close this issue.
Anyone against it?

**Comment by BeBel42** [comment]
It works on my side. I'll close it :+1:
