### ISSUE TITLE
Cancel button not updating its text even after being pressed

### ISSUE THREAD

**Issue by BeBel42** [maxdesalle/ft_transcendence#17]
When waiting for a game, pressing the big "Cancel..." button does nothing except changing the button animation.
The text should change to "Play", and the player should stop waiting for a game anymore.

**Comment by dbanziziki** [comment]
@BeBel42 fixed and on main just need some testing :)

**Comment by BeBel42** [comment]
@dbanziziki 
The little animation (the button going darker) is still playing after cancelling.

Press the button -> animation plays
Press cancel -> text updates but animation is still playing
Press play -> text is updated, and animation stops...
![Screenshot_20220823_224456](https://user-images.githubusercontent.com/64377698/186262117-014d0ce9-5b91-4cf1-8e6d-0f5a41e04ee3.png)

**Comment by dbanziziki** [comment]
@BeBel42 fixed on main
