### ISSUE TITLE
Impossible to log in after activating 2fa.

### ISSUE THREAD

**Issue by BeBel42** [maxdesalle/ft_transcendence#18]
Steps to reproduce:
- be on firefox
- login with 42
- activate 2fa on your account / scan the qr code
- press on "return to login"
- you cannot login again on that account.
Note that the bug also happens with the mock api

Here is the console output you get when logging in for the second time:
<img width="540" alt="Screen Shot 2022-08-21 at 4 59 43 PM" src="https://user-images.githubusercontent.com/64377698/185797452-0ce31ec5-2482-43d0-a03f-d0742776d6f0.png">
.

**Comment by dbanziziki** [comment]
@BeBel42 fixed it's on main you can test it and close the issue if it's good

**Comment by BeBel42** [comment]
@dbanziziki 
Bug found:
- Open edit profile (mock auth or 42 account)
- click activate 2fa
- Do not click on "go to login page", but rather click on the profile icon
- errors will appear and logging back in will not be possible
![2fabug2](https://user-images.githubusercontent.com/64377698/186260454-5e8aa7de-f6ba-4812-8cab-738957cb4da5.png)
![2fabug](https://user-images.githubusercontent.com/64377698/186260450-ffe5b5bf-b3b2-415b-a84a-b1fac50da628.png)

**Comment by dbanziziki** [comment]
@BeBel42  ok now I made it so you cant click anywhere else but the go back to login button, it's on main :)
