### ISSUE TITLE
Friends lists not updated

### ISSUE THREAD

**Issue by cammarosano** [maxdesalle/ft_transcendence#20]
When a friendship request is accepted, the new friend's username does not appear in the list "Invite a friend" unless the page is manually reloaded/refreshed.

@dbanziziki

**Comment by dbanziziki** [comment]
now the UI updates when
- a group is created
- a user is added/banned/promoted/demoted
- a friend request is accepted
- you block or unblock a friend or a room user

**Comment by cammarosano** [comment]
friend accept does update both sides friends list when the friendship invitation is sent via this button: 
![image](https://user-images.githubusercontent.com/65516503/187188721-05f36c4f-0093-499f-b0eb-822e2344a5fe.png)

But it does NOT get updated on the inviting side if the invitation is sent via this button: 
![image](https://user-images.githubusercontent.com/65516503/187188869-59606f01-0949-41ef-95a3-f295acf267a8.png)

**Comment by BeBel42** [comment]
@dbanziziki can I close this issue?

**Comment by dbanziziki** [comment]
Yep

**Comment by cammarosano** [comment]
I just tested it and... the bug is still there!

**Comment by dbanziziki** [comment]
now it's fixed

**Comment by cammarosano** [comment]
:(
Ok. Now watch closely:

![image](https://user-images.githubusercontent.com/65516503/188622277-395d5bb5-2555-41bc-9abc-a2080352a85e.png)

![Screenshot from 2022-09-06 13-14-33](https://user-images.githubusercontent.com/65516503/188622744-999663b0-10dd-48f6-9316-74db2284f1d8.png)

![Screenshot from 2022-09-06 13-14-45](https://user-images.githubusercontent.com/65516503/188622761-d243a4c0-17ef-4f78-a61f-7cc40d501e42.png)

![Screenshot from 2022-09-06 13-14-51](https://user-images.githubusercontent.com/65516503/188622773-57edd9ee-359a-48b7-a0a7-b4a5cefa5e8a.png)

![Screenshot from 2022-09-06 13-14-57](https://user-images.githubusercontent.com/65516503/188622788-155ca3a5-c4f7-48ff-b389-3498aa576188.png)

![Screenshot from 2022-09-06 13-15-03](https://user-images.githubusercontent.com/65516503/188622802-438d92b4-e5b2-4bb6-a034-9d2e376abde8.png)

![Screenshot from 2022-09-06 13-15-09](https://user-images.githubusercontent.com/65516503/188622815-a2e1d4b5-edd4-4760-b859-cce47a30d2db.png)

![Screenshot from 2022-09-06 13-15-14](https://user-images.githubusercontent.com/65516503/188622842-eab69b47-fb9a-4fef-a98a-fc7f53452c22.png)

**Comment by dbanziziki** [comment]
Fixed

**Comment by cammarosano** [comment]
good job!!
