### ISSUE TITLE
pong play - duplicate action?

### ISSUE THREAD

**Issue by cammarosano** [maxdesalle/ft_transcendence#21]
![image](https://user-images.githubusercontent.com/65516503/186040526-09ac948a-231e-4e73-b864-2fe1acf78cf6.png)

when a player is waiting (pressed "play") and a second player also presses play, a session is created and a match starts. Ok!
But the backend is detecting an action (play / invite / accepted) that is not expected when a player is currently playing. Such actions are protected by a guard (PongGuard), so nothing bad happens and an error message is logged. But the bottom line is: the frontend is doing an action that's not allowed (a user cannot ask to "play" when it's currently playing). 

Apparently, each one of the players is doing a new "play" request (via the pong wss), thus a duplicate request when it shouldn't.

@dbanziziki

**Comment by dbanziziki** [comment]
on my end I only send play once for each player and when a player is found I redirect both of them to /pong (I never perform double actions it's either play or cancel)

**Comment by cammarosano** [comment]
it might be something on my side, then... I'll investigate further.
