### ISSUE TITLE
pong sessions not removed

### ISSUE THREAD

**Issue by dbanziziki** [maxdesalle/ft_transcendence#22]
@cammarosano when a player gets disconnected, the other player stays in the session alone until the game ends and then the session is deleted

**Comment by cammarosano** [comment]
I'll check this later...
I suspect a big refactor of the matchmaking system is inevitable...
(this is related to the issue #10 )

**Comment by cammarosano** [comment]
![image](https://user-images.githubusercontent.com/65516503/187186641-074d41a0-3be2-4059-9444-6f0899e63414.png)

I made a quick and dirty fix. Now the game gets stopped, and the remaining user gets notified (see console log in the image above).

It's been already pushed to main. 
Is that enough for now?
