### ISSUE TITLE
Refactor matchmaking system

### ISSUE THREAD

**Issue by cammarosano** [maxdesalle/ft_transcendence#23]
Should we store sessions in an array and then iterate over it when doing a look up? Probably not. Maybe use a map<session_id, session_object>. Maybe other maps to index sockets to sessions too. Or maybe just use the "playing" set, made into a map to map to session ids.
And there are apparently 2 session / sockets array that must be have items removed upon a match end (normal, or early - disconnection).
Mind issue #22 .

**Comment by dbanziziki** [comment]
basically any data about that game must be removed and then you send a notification to the connected player.
if you only need the session id and the user id to clear everything then the 3rd option is good.
and for the connected user his status has to change

**Comment by cammarosano** [comment]
About the refactor: that would change considerably Martin's original code/logic. So it's better not to do it, otherwise I would be imposing my preferences over his.
For now, I'll leave it as it is.
