### ISSUE TITLE
pong CPU usage

### ISSUE THREAD

**Issue by cammarosano** [maxdesalle/ft_transcendence#24]
https://github.com/maxdesalle/ft_transcendence/blob/198e6aae70e524262e5bdbbce1c94322d8ceb8ba/frontend/src/pages/Pong.tsx#L20

@BeBel42, this line is evil!
As you probably know, this (0 ms) is what tells to browser to re-render the canvas as fast as it can. And CPU usage goes up to the skies...
if you set it to 10 ms, in theory, you already get a 100 fps refresh rate (should be enough for pong, right?)
Anyway, this is no bug, but I think being easier on the cpu would be a nice enhancement.

**Comment by BeBel42** [comment]
@dbanziziki Was the one who wrote that line :sweat_smile: But it was previously set to something like 100 I think? And it was laggy as hell... But if 10 seems good, then yeah, we can change this. I'll do it. We might as well use that remaining cpu for some bitcoin mining. Right? :wink:

**Comment by BeBel42** [comment]
Done and tested it. (just in case). Closing the issue now.
