### ISSUE TITLE
Choosing an already taken display-name is not handled by the frontend

### ISSUE THREAD

**Issue by cammarosano** [maxdesalle/ft_transcendence#25]
Backend returns the following response, on purpose, as display_name must be unique:
` {statusCode: 409, message: 'name already taken', error: 'Conflict'}`

Frontend does nothing about it!
@dbanziziki

**Comment by dbanziziki** [comment]
we need server side validation, if it's taken you can send a response that specifies that.
same for groups

**Comment by cammarosano** [comment]
That's exactly what's happening. "name already taken". 409 = conflict

**Comment by dbanziziki** [comment]
I cant get rid of the red error in the console but I can add a warning

**Comment by cammarosano** [comment]
I don't think it's a problem to have an error (4xx response) in the console, as long as you handle it. I suggest just alerting the user that the name is already taken and another one should be chosen. (That would be a way of handling it).

**Comment by dbanziziki** [comment]
ok it's done I pushed it on main

**Comment by cammarosano** [comment]
Nice! good job!
