### ISSUE TITLE
online/offline status in a room

### ISSUE THREAD

**Issue by cammarosano** [maxdesalle/ft_transcendence#26]
![image](https://user-images.githubusercontent.com/65516503/188484527-322c1a76-0bb8-4a4d-b22d-5804f7dd6a77.png)
In the image above, the user in the right ("helo") sees himself(!) and the group owner as offline. The group owner, on the other hand, sees both as online (and they are, indeed) for the same room.

**Comment by dbanziziki** [comment]
fixed

**Comment by cammarosano** [comment]
nice!
