### ISSUE TITLE
Creating groups with bad names

### ISSUE THREAD

**Issue by cammarosano** [maxdesalle/ft_transcendence#27]
![image](https://user-images.githubusercontent.com/65516503/188485340-fdbe7678-20a0-4fd3-a77e-43e204866c79.png)
Trying to create a room containing a ` ' ` is not allowed by the backend, as this would allow for SQL injection (David Szk 's chat uses raw SQL queries).

Shouldn't this be handled by the frontend with an alert or something? (like,  "bad name"!)

Another forbidden name for a group is a name that already exists:
![image](https://user-images.githubusercontent.com/65516503/188485741-ca097605-cd54-4405-a515-5f15623c66f3.png)

In both cases, the console log shows an uncaught exception. Shouldn't it handle it and inform the user that his action could not be done?

**Comment by dbanziziki** [comment]
the solution that I found is using regex and only accept name that contains letters and numbers only

**Comment by cammarosano** [comment]
The only constraint that I chose, doing sever side  validation, is to prohibit the single quote. And of course, not allow a duplicate group name.

The point is: the server responds a 400 (with a message), but the front-end does not handle it. And I know I never told you or documented this things, sorry.
So I suggest you check the response code and handle it, instead of letting an exception being uncaught.

**Comment by dbanziziki** [comment]
fixed added the warning

**Comment by cammarosano** [comment]
good! thanks!
