### ISSUE TITLE
2FA UX + console errors

### ISSUE THREAD

**Issue by cammarosano** [maxdesalle/ft_transcendence#32]
@dbanziziki , This could be a bit more clear to the user that he/she must enter the 2FA code... and maybe centered on the screen instead of on the corner? (just a suggestion)
![image](https://user-images.githubusercontent.com/65516503/188863345-5a788d74-37ab-4793-b627-341802b2b965.png)

And some error messages keep popping up in the console...
![image](https://user-images.githubusercontent.com/65516503/188863561-b26d1c34-c959-4c90-9e10-1cbf821bf5f2.png)

after some time... more errors...
![image](https://user-images.githubusercontent.com/65516503/188864440-5bc960ad-e247-487e-a208-efa0c3ac72bc.png)

**Comment by dbanziziki** [comment]
Fixed
