### ISSUE TITLE
No friend requests message

### ISSUE THREAD

**Issue by cammarosano** [maxdesalle/ft_transcendence#33]
![image](https://user-images.githubusercontent.com/65516503/188867621-0a1aa26a-bf24-4101-9467-14f260e3c103.png)
@dbanziziki 
This funny message makes more sense when the are no friend requests (notifications counter is zero).
But when there is a notification (a friend request) and you accept it (this was the case in this test) , this message also pops up (and makes little sense).
Of course this is no bug. If this is hard to change, I suggest just leaving as it is.

**Comment by dbanziziki** [comment]
left as it is
