### ISSUE TITLE
Pong broken?

### ISSUE THREAD

**Issue by cammarosano** [maxdesalle/ft_transcendence#34]
![image](https://user-images.githubusercontent.com/65516503/188868632-c3a02a18-dc3c-4666-ab47-f1a4550935a2.png)
@dbanziziki, @BeBel42 
I clicked "Play" in both sides, and this is what I got.

Log out both sides, and retried ("play" on each side):
![image](https://user-images.githubusercontent.com/65516503/188869175-06c95b68-8b36-4cad-a04c-c28ea56a06f6.png)

**Comment by cammarosano** [comment]
But... match seems to be happening somewhere.
![image](https://user-images.githubusercontent.com/65516503/188869436-48e6adce-5801-488d-931c-19718c0436ce.png)
![image](https://user-images.githubusercontent.com/65516503/188869510-9680ca19-4bdc-46f2-95a0-08db6e503abd.png)

**Comment by dbanziziki** [comment]
@cammarosano yeah i noticed that I am investigating the problem

**Comment by dbanziziki** [comment]
it's fixed
