### ISSUE TITLE
Blocking a useer that has blocked you

### ISSUE THREAD

**Issue by BeBel42** [maxdesalle/ft_transcendence#36]
When trying to block a friend that has already blocked you, the button will still be red and won't change (if you try to unblock the person) when you click on it until the other person has unblocked you...

**Comment by cammarosano** [comment]
I don't quite understand what you mean, @BeBel42. But there seems to be some button refresh issue/delay.

Anyway, this is what I think/propose how it should work:
- blocking is an action that each side can do. So, if user_1 blocks user_2, user_2 **"block" button should not change** and still be available. That means user_2 can also block user_1.
- So, each user can toggle it's own "block" button to "unblock" and vice-versa.
- a DM is blocked when: at least one of the two user has blocked the other.

What do you guys think?
If we agree on this, @dbanziziki tell me if you need new API endpoints...

**Comment by cammarosano** [comment]
rephrasing:
I think it's good how it is, I would just change the this:
user_1 press blocks, this changes his own button to "unblock", but nothing should change on user_2's side

**Comment by BeBel42** [comment]
Exactly. This would solve the issue 👍

**Comment by dbanziziki** [comment]
yep all good, I adjusted it a bit to get the live update

**Comment by BeBel42** [comment]
@dbanziziki You can close the issue when you fix it.
