### ISSUE TITLE
Demoting a normal member

### ISSUE THREAD

**Issue by BeBel42** [maxdesalle/ft_transcendence#38]
When I try to demote a normal user (least-privileged user) as the channel owner, my page freezes for 5-10 seconds do you experience the same issue?

**Comment by cammarosano** [comment]
Yes. After promoting and demoting a couple of times, I get this freeze when demoting or promoting (admin or normal user...). 
CPU usage raised.
The backend seems to be working normally though. (opening a different browser and using the app feels normal)

**Comment by dbanziziki** [comment]
@BeBel42 @cammarosano  it's fixed the UI was doing too many rerendering
