### ISSUE TITLE
Firefox cookies warning with 42 signins

### ISSUE THREAD

**Issue by BeBel42** [maxdesalle/ft_transcendence#39]
Firefox displays this issue

Cookie “jwt_token” with the “SameSite” attribute value “Lax” or “Strict” was omitted because of a cross-site redirect. localhost:3000

When loggin in with 42.

![warning_login_42](https://user-images.githubusercontent.com/64377698/190480374-a78ad571-cae8-4007-b1e4-cc0be7b02197.png)

**Comment by cammarosano** [comment]
@BeBel42, are you testing the production version? (docker-compose up --build) 
I don't get this error.

**Comment by BeBel42** [comment]
Yes I was. I can try it again when I have time this evening,

**Comment by BeBel42** [comment]
I was using Mozilla Firefox 105.0b9 (developer edition)

**Comment by BeBel42** [comment]
I cleared the cache and the cookies, deleted the images, containers and volume, made a git pull and docker-compose up --build, but I still have that warning... Am I really the only one? Maybe my versin is a bit too recent...

**Comment by dbanziziki** [comment]
[# export VITE_HOST=127.0.0.1](https://github.com/maxdesalle/ft_transcendence/blob/ef8a67c20421625346cc25700a4b7886017d8fb1/serve_static.sh#L1)
try to uncomment that line

**Comment by BeBel42** [comment]
I am sorry, but can you specify the file where that line is?

**Comment by dbanziziki** [comment]
in serve_static.sh

**Comment by BeBel42** [comment]
I did not see that it was a link 😅  It did not change anything. But isn't that obvious? I use docker-compose not serve_static... And serve_static is not used anywhere in the Dockerfile...

**Comment by dbanziziki** [comment]
fixed on the last push
