### ISSUE TITLE
chat rooms crossing messages

### ISSUE THREAD

**Issue by cammarosano** [maxdesalle/ft_transcendence#40]
![image](https://user-images.githubusercontent.com/65516503/190644729-ecaccabe-f084-4b2f-8233-1789fccd2ac0.png)

![image](https://user-images.githubusercontent.com/65516503/190644849-375ae4d2-5981-4f02-b2d5-4bfdec371d5a.png)

I sent a message in room TEST
And the message showed up on room HELLO

If I refresh the browser, the content of the rooms is corrected.
So I think it's related to the UI updating the content when new messages are received.

after refresh:
![image](https://user-images.githubusercontent.com/65516503/190645706-ea8ff9b4-a450-48b8-9d4f-e0f3c0f08256.png)

**Comment by dbanziziki** [comment]
@cammarosano it's all good now

**Comment by BeBel42** [comment]
@dbanziziki don't hesitate to close the issue after fixing it.
